# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 17:26
from __future__ import unicode_literals

import avatar.models
from django.db import migrations, models
import util.randomdirstorage


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0002_add_verbose_names_to_avatar_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(blank=True, max_length=1024, storage=util.randomdirstorage.S3PublicStorage(), upload_to=avatar.models.avatar_path_handler, verbose_name='avatar'),
        ),
    ]
